#! /usr/bin/env python
import yacc

import pyice_parser

from pyice_parser import ParseError
from pyice_lexer import LexError

import sys

class Compiler:

    def _parse(self, code):
        self.ast = yacc.parse(code)

    def compile(self, file):
        try:
            source = open(file, 'r')
            code = source.read()
            source.close
            self._parse(code)
        except ParseError, p:
            print >> sys.stderr, "line %d: syntax error near %s" % (p.lineno, p.token)
            sys.exit(1)
        except LexError, l:
            print >> sys.stderr, "line %d: illegal character %s" % (l.lineno, l.token)
            sys.exit(1)



def start_compiler():
    files = sys.argv[1:]

    for file in files:
        Compiler().compile(file)

if __name__ == '__main__':
    start_compiler()
