
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xfet\x98T\x04X\xbf\x0f\x1e\x9d>rL\xcb\x87$'
    
_lr_action_items = {'INT':([0,],[1,]),'RETURN':([0,],[3,]),'SEMI':([0,1,3,4,],[5,-4,6,7,]),'$end':([2,5,6,7,],[0,-3,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stm':([0,],[2,]),'exp':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stm","S'",1,None,None,None),
  ('stm -> RETURN SEMI','stm',2,'p_statement_02','pyice_parser.py',13),
  ('stm -> exp SEMI','stm',2,'p_statement_03','pyice_parser.py',16),
  ('stm -> SEMI','stm',1,'p_statement_04','pyice_parser.py',19),
  ('exp -> INT','exp',1,'p_expression','pyice_parser.py',22),
  ('empty -> <empty>','empty',0,'p_empty','pyice_parser.py',31),
]
